### ISSUE TITLE
GPGS Android: fetchLeaderboardEntries returns same values 

### ISSUE THREAD

**Issue by SimonIT** [MrStahlfelge/gdx-gamesvcs#22]
On my android phone, the leaderboard entries are always the same. If there are new values in the Google Play Games App, the old are given by fetchLeaderboardEntries, even if I clear the storage of my App. On the desktop are the entries up-to-date.

**Comment by MrStahlfelge** [comment]
Did you try to set forceRefresh to true?

**Comment by SimonIT** [comment]
This solved this problem, but now it doesn't load on one phone and on another phone, it takes 138 seconds

**Comment by MrStahlfelge** [comment]
Yes they work and are given to the GPGS API: [code here](https://github.com/MrStahlfelge/gdx-gamesvcs/blob/686fc4437e8647e7adf7957d9f356e8a070808f0/android-gpgs/src/de/golfgl/gdxgamesvcs/GpgsClient.java#L481) [Google's doc](https://developers.google.com/android/reference/com/google/android/gms/games/leaderboard/Leaderboards)

Unfortunately, the API _is_ slow. That's why there is the forceReload param. You should call the method with forceReload only when it is needed and not when the user is waiting for it.

**Comment by SimonIT** [comment]
Ok, thank you
